"'Product info' As screen":
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)

    Header_29 As Header:
        ScreenName: ="Product Info"

    "'Bottom Bar_31' As 'Bottom Bar'":
        Y: =1026
        ZIndex: =2

